#!/usr/bin/env node

const linklist = require('.')
const config = require('./conf.prod.json')
const ioServer = linklist.createServer(
  config['masterDbPath'],
  config['server']
)
console.log('started server')
